language: python

cache:
  - pip: True
  - directories:
    - $HOME/miniconda.tarball


python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"

install:
  # Updates
  - sudo apt-get update
  # Install a basic DM stack + obs_cfht
  - ./stack_install.sh
  # Prepare for other installs
  - export PATH="$HOME/miniconda/bin:$PATH"
  - source activate lsst
  - source eups-setups.sh
  # Install standard python packages
  - pip install codecov coveralls
  - pip install -r requirements.txt
  # Install Clusters
  - python setup.py install

# command to run tests
script:
  # Setup
  - export PATH="$HOME/miniconda/bin:$PATH"
  - source activate lsst
  - source eups-setups.sh
  - setup daf_persistence
  - setup obs_cfht -t travis
  # Get the test data
  - wget https://lapp-owncloud.in2p3.fr/index.php/s/xG2AoS2jggbmP0k/download
  - tar zxf download 
  - rm -rf download
  # Get LEPHARE
  - wget https://lapp-owncloud.in2p3.fr/index.php/s/MDaXObLSD9IVQ1B/download
  - tar zxf download
  - rm -rf download
  - mv lephare $HOME/
  # LEPHARE env. var.
  - export LEPHAREWORK="$HOME/lephare/lephare_work"
  - export LEPHAREDIR="$HOME/lephare/lephare_dev"
  - export PATH="$PATH:$HOME/lephare/lephare_dev/source"
  # Get PDZ
  - wget http://www.stsci.edu/~dcoe/BPZ/bpz-1.99.3.tar.gz
  - tar -xvf bpz-1.99.3.tar.gz
  - mv bpz-1.99.3 $HOME/
  - export BPZPATH="$HOME/bpz-1.99.3"
  - export PYTHONPATH=$PYTHONPATH:$BPZPATH
  - alias bpz="python $BPZPATH/bpz.py"
  - export NUMERIX=numpy
  # Run the tests
  - coverage run --source="clusters,pzmassfitter" setup.py test

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
  - rm -rf $HOME/.cache/pip/http

after_success:
  - codecov
  - coveralls

