language: python

cache:
  - pip
  - directories:
    - $HOME/miniconda.tarball


python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"

install:
  - sudo apt-get update
  #- CHANNEL=http://eupsforge.net/conda/dev ./stack_install.sh gcc lsst-daf-persistence lsst-log lsst-afw lsst-skypix lsst-meas-algorithms lsst-pipe-tasks
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda config --add channels http://conda.lsst.codes/stack
  - conda create -q -n lsst python=$TRAVIS_PYTHON_VERSION
  - source activate lsst
  # Install standard python packages
  - pip install pytest codecov coveralls
  - pip install -r requirements.txt
  # Install needed parts of the lsst stack
  - conda install -q gcc lsst-daf-persistence lsst-log lsst-afw lsst-skypix lsst-meas-algorithms lsst-pipe-tasks
  - source eups-setups.sh
  - setup daf_persistence
  # Install obs_cfht
  - mkdir my_packages
  - cd my_packages
  - git clone https://github.com/lsst/obs_cfht.git
  - cd obs_cfht
  - git checkout b7ab2c4
  - setup -k -r .
  - scons opt=3
  - eups declare -r . -t travis
  - cd ../..
  # Install Clusters
  - pip install .

# command to run tests
script:
  - export PATH="$HOME/miniconda/bin:$PATH"
  - source eups-setups.sh
  - setup daf_persistence
  - setup obs_cfht -t travis
  # Get the test data
  - wget https://lapp-owncloud.in2p3.fr/index.php/s/xG2AoS2jggbmP0k/download
  - tar zxvf download
  - rm -f download
  # Run the tests
  - coverage run --source="Clusters" setup.py test
  
after_success:
  - codecov
  - coveralls

