sudo: required

language: python

env:
  - REPOSITORY: docker.io/nchotard/clusters-test:centos7-stackv13
  - CONTAINER: lsststack
  
services:
  - docker
  
python:
  - "2.7"

before_install:
  - docker run -itd --name $CONTAINER -e "WORKDIR=/home/travis" -v "$PWD:/shared" $REPOSITORY
  
install:
  - pip install codecov

script:
  - docker exec $CONTAINER /bin/bash -c "/home/travis/torun.sh"

after_success:
  - codecov

