language: python

cache:
  - pip
  - directories:
    - $HOME/miniconda.tarball


python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"

install:
  # Updates
  - sudo apt-get update
  # Install a basic DM stack + obs_cfht
  - ./stack_install.sh
  # Prepare for other installs
  - export PATH="$HOME/miniconda/bin:$PATH"
  - source activate lsst
  - source eups-setups.sh
  # Install standard python packages
  - pip install --upgrade pytest codecov coveralls
  - pip install -r requirements.txt
  # Install Clusters
  - pip install .

# command to run tests
script:
  # Setup
  - export PATH="$HOME/miniconda/bin:$PATH"
  - source activate lsst
  - source eups-setups.sh
  - setup daf_persistence
  - setup obs_cfht -t travis
  # Get the test data
  - wget https://lapp-owncloud.in2p3.fr/index.php/s/xG2AoS2jggbmP0k/download
  - tar zxf download 
  - rm -rf download
  # Get LEPHARE
  - wget https://lapp-owncloud.in2p3.fr/index.php/s/MDaXObLSD9IVQ1B/download
  - tar zxf download
  - rm -rf download
  # LEPHARE env. var.
  - export LEPHAREWORK="$HOME/lephare/lephare_work"
  - export LEPHAREDIR="$HOME/lephare/lephare_dev"
  # Run the tests
  - coverage run --source="Clusters" setup.py test
  
after_success:
  - codecov
  - coveralls

